#!/usr/bin/env node
// Regenerates everything this repo derives from g2way, records what moved in
// UPSTREAM.md, updates the lock, and commits the result.
//
// g2way is the driver: this script is how its changes become a note here.
//
// Exit codes: 0 = done (or already in sync), 2 = refused (unsafe to record).

import { execFileSync } from 'node:child_process';
import { cpSync, existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import {
  LOCK_PATH,
  SHORT,
  commitsSince,
  computeDrift,
  headSha,
  isDirty,
  readLock,
  readWatch,
  repoRoot,
  resolveG2wayRepo,
  run,
  tryRun,
} from './g2way-lib.mjs';

const args = process.argv.slice(2);
const has = (f) => args.includes(f);
const repoFlag = has('--repo') ? args[args.indexOf('--repo') + 1] : null;
const noCommit = has('--no-commit');

const watch = readWatch();
const g2way = resolveG2wayRepo(watch, repoFlag);

function refuse(msg) {
  console.error(`sync:g2way refused: ${msg}`);
  process.exit(2);
}

if (!g2way.exists) refuse(`no g2way checkout at ${g2way.raw} (set G2WAY_REPO or pass --repo)`);

// A lock recorded against a dirty tree names OIDs that describe committed
// state nobody can reproduce from that working copy.
if (isDirty(g2way.path))
  refuse(`${g2way.path} has uncommitted changes — commit or stash them first`);

// The commit this makes must contain only sync output.
const staged = run('git', ['-C', repoRoot, 'diff', '--cached', '--name-only']);
if (!noCommit && staged.length > 0) {
  refuse(
    `this repo has staged changes:\n  ${staged.split('\n').join('\n  ')}\nCommit them first, or pass --no-commit.`,
  );
}

const head = headSha(g2way.path);
const lock = readLock();
const drift = computeDrift(g2way.path, watch, lock);
const changed = drift.filter((d) => d.drifted);
const first = lock === null;

if (!first && changed.length === 0 && lock.head === head) {
  console.log(`Already in sync with g2way ${SHORT(head)}.`);
  process.exit(0);
}

// ---- regenerate derived artifacts ---------------------------------------

const contracts = resolve(repoRoot, 'contracts');
mkdirSync(contracts, { recursive: true });

// Read the spec g2way commits, rather than running `make openapi` there. The
// upstream repo is strictly read-only to this script: regenerating in place
// would dirty someone else's working tree, and that target's shell redirect
// truncates the file before cargo runs, so a broken upstream build would
// destroy the committed spec. Reading the committed blob also means this repo
// needs no Rust toolchain.
console.log('Reading the committed OpenAPI contract...');
const spec = tryRun('git', ['-C', g2way.path, 'show', 'HEAD:docs/api/openapi.json']);
if (spec === null) {
  refuse('g2way HEAD has no docs/api/openapi.json — run `make openapi` there and commit it');
}
writeFileSync(resolve(contracts, 'openapi.json'), spec.endsWith('\n') ? spec : `${spec}\n`);

console.log('Generating TypeScript types...');
const types = execFileSync(
  'npx',
  ['--yes', 'openapi-typescript', resolve(contracts, 'openapi.json')],
  { encoding: 'utf8', cwd: repoRoot },
);
writeFileSync(
  resolve(contracts, 'g2way.d.ts'),
  `// GENERATED by \`npm run sync:g2way\` from contracts/openapi.json — do not edit.\n` +
    `// Source: g2way ${head}\n\n${types}`,
);

console.log('Vendoring g2way docs...');
const docsDir = resolve(contracts, 'g2way-docs');
rmSync(docsDir, { recursive: true, force: true });
mkdirSync(resolve(docsDir, 'adr'), { recursive: true });
for (const rel of run('git', [
  '-C',
  g2way.path,
  'ls-tree',
  '-r',
  '--name-only',
  'HEAD',
  'docs/',
]).split('\n')) {
  if (!rel.endsWith('.md')) continue;
  const dest = resolve(docsDir, rel.replace(/^docs\//, ''));
  mkdirSync(resolve(dest, '..'), { recursive: true });
  cpSync(resolve(g2way.path, rel), dest);
}
writeFileSync(
  resolve(docsDir, 'README.md'),
  `# Vendored g2way docs\n\nCopied verbatim from g2way \`${head}\` by \`npm run sync:g2way\`.\n` +
    `Do not edit — change them upstream and re-sync.\n\nThey are vendored so Claude can read them without\n` +
    `leaving this repo, and so the explain panels can render them in a container that has no g2way checkout.\n`,
);

// ---- write the note ------------------------------------------------------

const today = new Date().toISOString().slice(0, 10);
const upstreamPath = resolve(repoRoot, 'UPSTREAM.md');
const areasChanged = first ? watch.areas.map((a) => a.id) : changed.map((d) => d.area.id);

let entry = `\n## ${today} — g2way ${SHORT(lock?.head)} → ${SHORT(head)}\n\n`;
if (first) {
  entry +=
    `Initial lock against g2way \`${head}\`. All ${watch.areas.length} watched areas recorded; ` +
    `no drift to report yet.\n`;
} else {
  entry +=
    areasChanged.length > 0
      ? `Watched areas changed: **${areasChanged.join(', ')}**\n`
      : `Upstream moved, but no watched area changed. Lock advanced; nothing to do here.\n`;
  for (const d of changed) {
    entry += `\n### ${d.area.id}\n\n`;
    entry += `- Drives: ${d.area.surfaces.join(', ')}\n`;
    entry += `- Action: ${d.area.onChange}\n`;
    const commits = commitsSince(g2way.path, lock.head, d.area);
    if (commits.length > 0) {
      entry += `- Upstream commits:\n`;
      for (const c of commits) entry += `  - \`${c}\`\n`;
    }
    entry += `- [ ] TODO: ${d.area.onChange}\n`;
  }
}

const header = `# Upstream (g2way) journal

g2way is the driver for this project. Every time a watched area of it changes,
\`npm run sync:g2way\` regenerates \`contracts/\` and appends an entry below.

Entries are append-only history — never rewrite one. Tick the \`TODO\` boxes as the
dashboard catches up; those are the open work items this journal exists to track.

Watched areas are defined in \`contracts/watch.json\`; the recorded fingerprints live
in \`contracts/g2way.lock.json\`. Run \`npm run check:g2way\` to see whether we are behind.
`;

if (existsSync(upstreamPath)) {
  writeFileSync(upstreamPath, readFileSync(upstreamPath, 'utf8').trimEnd() + '\n' + entry);
} else {
  writeFileSync(upstreamPath, header + entry);
}

// ---- update the lock -----------------------------------------------------

const areas = {};
for (const d of drift) areas[d.area.id] = { oid: d.oid };
writeFileSync(
  LOCK_PATH,
  JSON.stringify(
    {
      $comment: 'GENERATED by `npm run sync:g2way` — do not edit by hand.',
      head,
      syncedAt: today,
      areas,
    },
    null,
    2,
  ) + '\n',
);

// ---- commit --------------------------------------------------------------

const paths = ['contracts', 'UPSTREAM.md'];
if (noCommit) {
  console.log(`\nUpdated ${paths.join(', ')} (--no-commit: nothing committed).`);
  process.exit(0);
}

run('git', ['-C', repoRoot, 'add', ...paths]);
if (run('git', ['-C', repoRoot, 'diff', '--cached', '--name-only']).length === 0) {
  console.log('Nothing changed on disk; no commit made.');
  process.exit(0);
}

const subject = first
  ? `chore(upstream): lock to g2way ${SHORT(head)} — initial contract sync`
  : areasChanged.length > 0
    ? `chore(upstream): sync to g2way ${SHORT(head)} — ${areasChanged.join(', ')}`
    : `chore(upstream): sync to g2way ${SHORT(head)} — no watched area changed`;

let body = first
  ? `Records the first fingerprint of all ${watch.areas.length} watched g2way areas and\ngenerates contracts/ from g2way ${SHORT(head)}.\n`
  : areasChanged.length === 0
    ? `g2way moved to ${SHORT(head)} without touching a watched area; the lock is advanced\nso future drift is measured from here.\n`
    : `Watched areas changed: ${areasChanged.join(', ')}\n\n` +
      changed
        .map((d) => {
          const commits = commitsSince(g2way.path, lock.head, d.area);
          return (
            `${d.area.id} — drives ${d.area.surfaces.join(', ')}\n` +
            commits.map((c) => `  ${c}`).join('\n')
          );
        })
        .join('\n\n') +
      '\n';

body += `\nSee UPSTREAM.md for the journal entry and any open TODOs.\n\nG2way-Upstream: ${head}\n`;

execFileSync('git', ['-C', repoRoot, 'commit', '-q', '-m', subject, '-m', body], {
  stdio: 'inherit',
});
console.log(`\nCommitted: ${subject}`);
